import "./globals.css";
import { AuthProvider } from "./AuthContext";

export const metadata = {
  title: "Set My Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="bg-white">{children}</body>
      </html>
    </AuthProvider>
  );
}
